#!/bin/sh
#
# Copy required files to the Emacspeak directory pointed with SOURCE_DIR.
#
. devel/settings
# Make directory
for d in $ADDITIONAL_DIR; do
if [ ! -d $SOURCE_DIR/$d ]; then
mkdir -p $SOURCE_DIR/$d
fi
done
#
files=`cat $DIFF_LIST`
for f in $files; do
cp -pv $f $SOURCE_DIR/$f
done
