#!/bin/sh
# Remove some files from Emacspeak directory to avoid update problem
#
. devel/settings
#
files=`cat $REMOVE_LIST`
(cd $SOURCE_DIR && rm -rf $files)
for d in $ADDITIONAL_DIR; do
if [ -d $SOURCE_DIR/$d ]; then
rm -rf $SOURCE_DIR/$d
fi
done

